- hosts: cumulus-nodes
  name: startup
  become: yes
  gather_facts: no
  tasks:
    - name: clean startup.yaml
      copy:
        src: /home/cumulus/ON-10/cleanup/{{ inventory_hostname }}.yaml
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes for all cumulus nodes
      shell:  nv config apply startup -y
      
    - name: uninstall nginx
      apt:
        name: nginx
        state: absent

    - name: stop nginx
      service:
        name: nginx
        state: stopped
