# 14-MAY-2021, preparing the 2 switches with L2, bonding, bridge configuration
# 14-MAY-2021, hands-on via task-001.yaml and should include spine3 and leaf1
# 14-NOV-2021, cleaning up a bit

- hosts: cumulus-nodes
  name: startup
  become: yes
  gather_facts: no
  tasks:
    - name: copy leaf1 task-01.yaml
      copy:
        src: /home/cumulus/ON-10/step-01/task-01-{{ inventory_hostname }}.yaml
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes for leaf
      shell: nv config apply startup -y
