# 08-APR-2022, index.html, test-script
# 14-MAY-2022, preparing the 2 switches with L2, bonding, bridge configuration
# 14-MAY-2022, hands-on via task-001.yaml and should include spine3 and leaf1
# 14-NOV-2021, cleaning up a bit
# 01-DEC-2021, updated bridge configuration 

- hosts: cumulus-nodes
  name: startup
  become: yes
  gather_facts: no
  tasks:
    - name: copy leaf1 task-01.yaml
      copy:
        src: /home/cumulus/ON-10/step-01/{{ inventory_hostname }}.yaml
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes for leaf
      shell: nv config apply startup -y
      
- hosts: host
  name: netplan
  become: yes
  gather_facts: no
  tasks:
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/ON-10/step-01/{{ inventory_hostname }}
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml
      shell: netplan apply

- hosts: host
  name: index
  become: yes
  gather_facts: no
  tasks:
    - name: copy index.html 
      copy:
        src: /home/cumulus/ON-10/step-01/index.html
        dest: /var/www/html/index.html
    - name: python test script
      copy: 
        src: /home/cumulus/ON-10/step-01/test_script.py
        dest: /home/cumulus/test_script.py
        mode: a+x
