# 28-APRIL-2021, preparing the 4 hosts with IPv4 addresses
# 13-NOVEMER-2021, rewritten a bit

- hosts: host
  name: Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: configure IPv4 address and route
      copy:
        src: /home/cumulus/ON-10/inventory/files/{{ inventory-hostname }}
        dest: /etc/network/interfaces
    - name: activate changes 
      ansible.builtin.shell: /sbin/ifreload -a
    - name: verify
      ansible.builtin.shell: /sbin/ip -br a
      register: ipa
    - debug: msg={{ ipa.stdout }}
