- hosts: host
  name: netplan
  become: yes
  gather_facts: no
  tasks:
    - name: cloud file entfernen
      ansible.builtin.file:
        path: /etc/netplan/50-cloud-init.yaml
        state: absent
    - name: cloud file entfernen
      ansible.builtin.file:
        path: /etc/netplan/config.yaml
        state: absent
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/ON-10/step-00/{{ inventory_hostname }}
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml
      shell: netplan apply
       
    - name: Check interface 2
      shell: /sbin/ip -br -4 a | grep 'eth2'
      ignore_errors: yes
      register: result
    - debug: msg={{ result.stdout }}
  
    - name: www
      apt:
        name: nginx
        update_cache: yes

- hosts: cumulus-nodes
  name: startup
  become: yes
  gather_facts: no
  tasks:
    - name: copy startup.yaml
      copy:
        src: /home/cumulus/ON-10/step-00/{{ inventory_hostname }}
        dest: /etc/nvue.d/startup.yaml
    # aktivieren
    - name: activate changes for leaf
      shell:  nv config apply startup -y
      
# optional lab task      
      
- hosts: leaf1
  name: configuring of PTM
  become: yes
  gather_facts: no
  tasks:
    - name: PTM
      copy:
        src: /home/cumulus/ON-10/inventory/files/topology.dot
        dest: /etc/ptm.d/topology.dot
        mode: '0644'
        owner: 'root'
        group: 'root'
      notify: restart_ptm

  handlers:
    - name: restart_ptm
      service:
        name=ptmd
        state=restarted
      listen: restart_ptm

# nginx

- hosts: leaf1
  name: nginx
  become: yes
  gather_facts: no
  tasks:
    - name: www
      apt:
        name: nginx
        update_cache: yes

    # aktivieren
#    - name: nginx-1
#      shell: ln -s /etc/nginx/sites-{available,enabled}/nvue.conf
#    - name: nginx-2
#      shell: sed -i 's/listen localhost:8765 ssl;/listen \[::\]:8765 ipv6only=off ssl;/g' /etc/nginx/sites-available/nvue.conf
#    - name: nginx-3
#      shell: systemctl restart nginx
    
# 08.04.2022: ok    
# curl  -u 'cumulus:Academy123' --insecure https://172.16.1.10:8765/cue_v1/interface
