# 28-APRIL-2021, preparing the 4 hosts with IPv4 addresses
# 13-NOVEMBER-2021, rewritten a bit
# 14-NOV moved host files again
# 21-MAR-2022 wechsel zu Netplan

#- hosts: host
#  name: Interfaces
#  become: yes
#  gather_facts: no
#  tasks:
#    - name: configure IPv4 address and route
#      copy:
#        src: /home/cumulus/ON-10/step-00/{{ inventory_hostname }}
#        dest: /etc/network/interfaces
#    - name: activate changes 
#      ansible.builtin.shell: /sbin/ifreload -a


- hosts: host
  name: netplan
  become: yes
  gather_facts: no
  tasks:
    - name: cloud file entfernen
      ansible.builtin.file:
        path: /etc/netplan/50-cloud-init.yaml
        state: absent
    - name: cloud file entfernen
      ansible.builtin.file:
        path: /etc/netplan/config.yaml
        state: absent
    - name: copy netplan yaml
      copy:
        src: /home/cumulus/ON-10/step-00/{{ inventory_hostname }}
        dest: /etc/netplan/config.yaml
    - name: apply netplan yaml
      shell: netplan apply
      
#    - name: verify
#      ansible.builtin.shell: /sbin/ip -br a
#      register: ipa
#    - debug: msg={{ ipa.stdout }}
       
    - name: Check interface 2
      shell: /sbin/ip -br -4 a | grep 'eth2'
      ignore_errors: yes
      register: result
    - debug: msg={{ result.stdout }}
