# 06-AUG-2021 NVUE  

- hosts: cumulus-nodes
  name: disable NCLU and enable NVUE
  become: yes
  gather_facts: no
  tasks:
    - name: stop NCLU
      shell: systemctl stop netd
    - name: disable NCLU
      shell: systemctl disable netd
    - name: enable NVUE was CUE
      shell: systemctl enable nvued
    - name: start NVUE was CUE
      shell: systemctl start nvued   
