- hosts: host
  name: netplan
  become: yes
  gather_facts: no
  tasks:
    - name: www
      apt:
        name: nginx
        update_cache: yes
    - name: copy index.html 
      copy:
        src: /home/cumulus/ON-10/step-01/index.html
        dest: /var/www/html/index.html
    - name: python test script
      copy: 
        src: /home/cumulus/ON-10/step-01/test_script.py
        dest: /home/cumulus/test_script.py
        mode: a+x


# aktivieren
#    - name: nginx-1
#      shell: ln -s /etc/nginx/sites-{available,enabled}/nvue.conf
#    - name: nginx-2
#      shell: sed -i 's/listen localhost:8765 ssl;/listen \[::\]:8765 ipv6only=off ssl;/g' /etc/nginx/sites-available/nvue.conf
#    - name: nginx-3
#      shell: systemctl restart nginx
    
# 08.04.2022: ok    
# curl  -u 'cumulus:Academy123' --insecure https://172.16.1.10:8765/cue_v1/interface
